# Generated by Django 4.1.7 on 2023-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitet', models.CharField(max_length=100)),
                ('beskrivelse', models.CharField(max_length=100)),
                ('starttidspunkt', models.DateTimeField()),
                ('sluttidspunkt', models.DateTimeField()),
                ('antalpersoner', models.IntegerField()),
                ('pris', models.IntegerField()),
                ('oprettelsestidspunkt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
