# Generated by Django 4.1.7 on 2023-04-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aktivitet_remove_profile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitet',
            name='antalpersoner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='pris',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='sluttidspunkt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='starttidspunkt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
