# Generated by Django 4.1.7 on 2023-04-15 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_aktivitet_antalpersoner_alter_aktivitet_pris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='starttidspunkt',
            field=models.DateTimeField(),
        ),
    ]
